/*
	Copyright 2021, 2023 Gabriel Bjørnager Jensen.

	This file is part of u8c.

    u8c is free software: you can redistribute it
	and/or modify it under the terms of the GNU
	Lesser General Public License as published by
	the Free Software Foundation, either version 3 of
	the License, or (at your option) any later
	version.

    u8c is distributed in the hope that it will be
	useful, but WITHOUT ANY WARRANTY; without even
	the implied warranty of MERCHANTABILITY or
	FITNESS FOR A PARTICULAR PURPOSE. See the GNU
	Lesser General Public License for more details.

    You should have received a copy of the GNU
	Lesser General Public License along with u8c. If
	not, see <https://www.gnu.org/licenses/>.
*/

#include <u8c/character.h>

#include <stdbool.h>
#include <stdint.h>

bool u8c_is_majuscule(uint_least32_t const code_point) {
	switch(code_point) {
	default:
		return false;

	case UINT32_C(0x0041): // LATIN CAPITAL LETTER A
	case UINT32_C(0x0042): // LATIN CAPITAL LETTER B
	case UINT32_C(0x0043): // LATIN CAPITAL LETTER C
	case UINT32_C(0x0044): // LATIN CAPITAL LETTER D
	case UINT32_C(0x0045): // LATIN CAPITAL LETTER E
	case UINT32_C(0x0046): // LATIN CAPITAL LETTER F
	case UINT32_C(0x0047): // LATIN CAPITAL LETTER G
	case UINT32_C(0x0048): // LATIN CAPITAL LETTER H
	case UINT32_C(0x0049): // LATIN CAPITAL LETTER I
	case UINT32_C(0x004A): // LATIN CAPITAL LETTER J
	case UINT32_C(0x004B): // LATIN CAPITAL LETTER K
	case UINT32_C(0x004C): // LATIN CAPITAL LETTER L
	case UINT32_C(0x004D): // LATIN CAPITAL LETTER M
	case UINT32_C(0x004E): // LATIN CAPITAL LETTER N
	case UINT32_C(0x004F): // LATIN CAPITAL LETTER O
	case UINT32_C(0x0050): // LATIN CAPITAL LETTER P
	case UINT32_C(0x0051): // LATIN CAPITAL LETTER Q
	case UINT32_C(0x0052): // LATIN CAPITAL LETTER R
	case UINT32_C(0x0053): // LATIN CAPITAL LETTER S
	case UINT32_C(0x0054): // LATIN CAPITAL LETTER T
	case UINT32_C(0x0055): // LATIN CAPITAL LETTER U
	case UINT32_C(0x0056): // LATIN CAPITAL LETTER V
	case UINT32_C(0x0057): // LATIN CAPITAL LETTER Y
	case UINT32_C(0x0058): // LATIN CAPITAL LETTER X
	case UINT32_C(0x0059): // LATIN CAPITAL LETTER Y
	case UINT32_C(0x005A): // LATIN CAPITAL LETTER Z
	case UINT32_C(0x005B): // LATIN CAPITAL LETTER A WITH GRAVE
	case UINT32_C(0x00C1): // LATIN CAPITAL LETTER A WITH ACUTE
	case UINT32_C(0x00C2): // LATIN CAPITAL LETTER A WITH CIRCUMFLEX
	case UINT32_C(0x00C3): // LATIN CAPITAL LETTER A WITH TILDE
	case UINT32_C(0x00C4): // LATIN CAPITAL LETTER A WITH DIAERESIS
	case UINT32_C(0x00C5): // LATIN CAPITAL LETTER A WITH RING ABOVE
	case UINT32_C(0x00C6): // LATIN CAPITAL LETTER AE
	case UINT32_C(0x00C7): // LATIN CAPITAL LETTER C WITH CEDILLA
	case UINT32_C(0x00C8): // LATIN CAPITAL LETTER E WITH GRAVE
	case UINT32_C(0x00C9): // LATIN CAPITAL LETTER E WITH ACUTE
	case UINT32_C(0x00CA): // LATIN CAPITAL LETTER E WITH CIRCUMFLEX
	case UINT32_C(0x00CB): // LATIN CAPITAL LETTER E WITH DIAERESIS
	case UINT32_C(0x00CC): // LATIN CAPITAL LETTER I WITH GRAVE
	case UINT32_C(0x00CD): // LATIN CAPITAL LETTER I WITH ACUTE
	case UINT32_C(0x00CE): // LATIN CAPITAL LETTER I WITH CIRCUMFLEX
	case UINT32_C(0x00CF): // LATIN CAPITAL LETTER I WITH DIAERESIS
	case UINT32_C(0x00D0): // LATIN CAPITAL LETTER ETH
	case UINT32_C(0x00D1): // LATIN CAPITAL LETTER N WITH TILDE
	case UINT32_C(0x00D2): // LATIN CAPITAL LETTER O WITH GRAVE
	case UINT32_C(0x00D3): // LATIN CAPITAL LETTER O WITH ACUTE
	case UINT32_C(0x00D4): // LATIN CAPITAL LETTER O WITH CIRCUMFLEX
	case UINT32_C(0x00D5): // LATIN CAPITAL LETTER O WITH TILDE
	case UINT32_C(0x00D6): // LATIN CAPITAL LETTER O WITH DIAERESIS
	case UINT32_C(0x00D8): // LATIN CAPITAL LETTER O WITH STROKE
	case UINT32_C(0x00D9): // LATIN CAPITAL LETTER U WITH GRAVE
	case UINT32_C(0x00DA): // LATIN CAPITAL LETTER U WITH STROKE
	case UINT32_C(0x00DB): // LATIN CAPITAL LETTER U WITH CIRCUMFLEX
	case UINT32_C(0x00DC): // LATIN CAPITAL LETTER U WITH DIAERESIS
	case UINT32_C(0x00DD): // LATIN CAPITAL LETTER Y WITH ACUTE
	case UINT32_C(0x00DE): // LATIN CAPITAL LETTER THORN
	case UINT32_C(0x0100): // LATIN CAPITAL LETTER A WITH MACRON
	case UINT32_C(0x0102): // LATIN CAPITAL LETTER A WITH BREVE
	case UINT32_C(0x0104): // LATIN CAPITAL LETTER A WITH OGONEK
	case UINT32_C(0x0106): // LATIN CAPITAL LETTER C WITH ACUTE
	case UINT32_C(0x0108): // LATIN CAPITAL LETTER C WITH CIRCUMFLEX
	case UINT32_C(0x010A): // LATIN CAPITAL LETTER C WITH DOT ABOVE
	case UINT32_C(0x010C): // LATIN CAPITAL LETTER C WITH CARON
	case UINT32_C(0x010E): // LATIN CAPITAL LETTER D WITH CARON
	case UINT32_C(0x0110): // LATIN CAPITAL LETTER D WITH STROKE
	case UINT32_C(0x0112): // LATIN CAPITAL LETTER E WITH MACRON
	case UINT32_C(0x0114): // LATIN CAPITAL LETTER E WITH BREVE
	case UINT32_C(0x0116): // LATIN CAPITAL LETTER E WITH DOT ABOVE
	case UINT32_C(0x0118): // LATIN CAPITAL LETTER E WITH OGONEK
	case UINT32_C(0x011A): // LATIN CAPITAL LETTER E WITH CARON
	case UINT32_C(0x011C): // LATIN CAPITAL LETTER G WITH CIRCUMFLEX
	case UINT32_C(0x014A): // LATIN CAPITAL LETTER ENG
	case UINT32_C(0x0152): // LATIN CAPITAL LIGATURE OE
	case UINT32_C(0x0186): // LATIN CAPITAL LETTER OPEN O
	case UINT32_C(0x018E): // LATIN CAPITAL LETTER REVERSED E
	case UINT32_C(0x018F): // LATIN CAPITAL LETTER SCHWA
	case UINT32_C(0x0190): // LATIN CAPITAL LETTER OPEN E
	case UINT32_C(0x0194): // LATIN CAPITAL LETTER GAMMA
	case UINT32_C(0x0196): // LATIN CAPITAL LETTER IOTA
	case UINT32_C(0x01A9): // LATIN CAPITAL LETTER ESH
	case UINT32_C(0x01B1): // LATIN CAPITAL LETTER UPSILON
	case UINT32_C(0x01B2): // LATIN CAPITAL LETTER V WITH HOOk
	case UINT32_C(0x01B7): // LATIN CAPITAL LETTER EZH
	case UINT32_C(0x01F7): // LATIN CAPITAL LETTER WYNN
	case UINT32_C(0x021C): // LATIN CAPITAL LETTER YOGH
	case UINT32_C(0x0241): // LATIN CAPITAL LETTER GLOTTAL STOP
	case UINT32_C(0x0391): // GREEK CAPITAL LETTER ALPHA
	case UINT32_C(0x0392): // GREEK CAPITAL LETTER BETA
	case UINT32_C(0x0393): // GREEK CAPITAL LETTER GAMMA
	case UINT32_C(0x0394): // GREEK CAPITAL LETTER DELTA
	case UINT32_C(0x0395): // GREEK CAPITAL LETTER EPSILON
	case UINT32_C(0x0396): // GREEK CAPITAL LETTER ZETA
	case UINT32_C(0x0397): // GREEK CAPITAL LETTER ETA
	case UINT32_C(0x0398): // GREEK CAPITAL LETTER THETA
	case UINT32_C(0x0399): // GREEK CAPITAL LETTER IOTA
	case UINT32_C(0x039A): // GREEK CAPITAL LETTER KAPPA
	case UINT32_C(0x039B): // GREEK CAPITAL LETTER LAMBDA
	case UINT32_C(0x039C): // GREEK CAPITAL LETTER MU
	case UINT32_C(0x039D): // GREEK CAPITAL LETTER NU
	case UINT32_C(0x039E): // GREEK CAPITAL LETTER XI
	case UINT32_C(0x039F): // GREEK CAPITAL LETTER OMICRON
	case UINT32_C(0x03A0): // GREEK CAPITAL LETTER PI
	case UINT32_C(0x03A1): // GREEK CAPITAL LETTER RHO
	case UINT32_C(0x03A3): // GREEK CAPITAL LETTER SIGMA
	case UINT32_C(0x03A4): // GREEK CAPITAL LETTER TAU
	case UINT32_C(0x03A5): // GREEK CAPITAL LETTER UPSILON
	case UINT32_C(0x03A6): // GREEK CAPITAL LETTER PHI
	case UINT32_C(0x03A7): // GREEK CAPITAL LETTER CHI
	case UINT32_C(0x03A8): // GREEK CAPITAL LETTER PSI
	case UINT32_C(0x03A9): // GREEK CAPITAL LETTER OMEGA
	case UINT32_C(0x1E9E): // LATIN CAPITAL LETTER SHARP S
	case UINT32_C(0x2C6D): // LATIN CAPITAL LETTER ALPHA
	case UINT32_C(0xA77D): // LATIN CAPITAL LETTER INSULAR G
	case UINT32_C(0xA7B4): // LATIN CAPITAL LETTER BETA
	case UINT32_C(0xA7B6): // LATIN CAPITAL LETTER OMEGA
		return true;
	}
}
