.TH "u8c_abrt" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_abrt - Abort - Abort program with diagnostic information.
.SH DECLARATION
.PP
.nf
\f[C]
/* # include <u8c/main.h> */
# include <u8c/main.h
# define u8c_abrt(why) u8c_abrtfn(__FILE__,(long)__LINE__,__func__,why)
\f[R]
.fi
.SH DESCRIPTION
.PP
The macro \f[B]u8c_abrt\f[R] expands to a valid call to \f[B]u8c_abrtfn\f[R].
.SH VERSION
.PP
u8c 21
