.TH "u8c_u16free" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_u16free - UTF-16 free - Deallocate UTF-16 string and set it to \f[B]NULL\f[R].
.SH DECLARATION
.PP
.nf
\f[C]
/* # include <u8c/u16.h> */
# include <stdbool.h>
# include <uchar.h>
extern bool u8c_u16free(char16_t const * * const u16);
\f[R]
.fi
.SH DESCRIPTION
.PP
.SH VERSION
.PP
u8c 20
