.TH "u8c_unimax" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_unimax - Unicode maximum - Maximum valid Unicode codepoint.
.SH DECLARATION
.PP
.nf
\f[C]
/* # include <u8c/main.h> */
# include <stdint.h>
# include <uchar.h>
# define u8c_unimax ((char32_t)UINT32_C(0x10FFFF))
\f[R]
.fi
.SH DESCRIPTION
.PP
.SH VERSION
.PP
u8c 16
