.TH "u8c_isxdigit" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_isxdigit - Is hexadecimal digit - Check if a character is a hexadecimal digit.
.SH DECLARATION
.PP
.nf
\f[C]
# include <stdbool.h>
# include <stdint.h>
# include <uchar.h>
extern bool u8c_isxdigit(uint_least8_t * const res,char32_t const chr);
\f[R]
.fi
.SH DESCRIPTION
.PP
.SH VERSION
.PP
u8c 16
