.TH "u8c_fmt" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_fmt - Format - Format UTF-32 string.
.SH DECLARATION
.PP
.nf
\f[C]
/* # include <u8c/fmt.h> */
# include <stddef.h>
# include <uchar.h>
extern bool u8c_fmt(size_t * const outsz,char32_t const * * const out,char32_t const * const in,...);
\f[R]
.fi
.SH DESCRIPTION
.PP
.SH VERSION
.PP
u8c 2
