.TH "u8c_println" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_println - Print line - Format UTF-32 and print it to file (followed by a new-line).
.SH DECLARATION
.PP
.nf
\f[C]
# include <stdbool.h>
# include <stdio.h>
# include <uchar.h>
extern bool u8c_println(FILE * fp,char32_t const * const msg,...);
\f[R]
.fi
.SH DESCRIPTION
.PP
.SH VERSION
.PP
u8c 0 (as u8c_print), u8c 2
