.TH "u8c_vprint" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_vprint - Variadic print - Format UTF-32 and print it to file.
.SH DECLARATION
.PP
.nf
\f[C]
/* # include <u8c/fmt.h> */
# include <stdarg.h>
# include <stdbool.h>
# include <stdio.h>
# include <uchar.h>
extern bool u8c_vprint(FILE * fp,char32_t const * const msg,va_list args);
\f[R]
.fi
.SH DESCRIPTION
.PP
.SH VERSION
.PP
u8c 2
