.TH "u8c_u32cat" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_u32cat - UTF-32 concatenate - Concatenate two UTF-32 strings.
.SH DECLARATION
.PP
.nf
\f[C]
# include <stdbool.h>
# include <stddef.h>
# include <uchar.h>
extern bool u8c_u32cat(size_t * const sz,char32_t const * * const out,char32_t const * const lstr,char32_t const * const rstr);
\f[R]
.fi
.SH DESCRIPTION
.PP
.SH VERSION
.PP
u8c 16
