.TH "u8c_regerrhandl" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_regerrhandl - Register error handler - Register error handler function to be called by \f[B]u8c_seterr\f[R].
.SH DECLARATION
.PP
.nf
\f[C]
/* # include <u8c/err.h> */
# include <stdbool.h>
# include <u8c/errhandltyp.h>
# include <u8c/errtyp.h>
extern bool u8c_regerrhandl(enum u8c_errtyp typ,u8c_errhandltyp errhandl);
\f[R]
.fi
.SH DESCRIPTION
.PP
Registers an error handler to be called when an error of type \f[B]typ\f[R] is detected.
.PP
If \f[B]u8c_errtyp_all\f[R] is passed at \f[B]typ\f[R], the error handler is registered for all error types.
.SH VERSION
.PP
u8c 19
