.TH "u8c_isalpha" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_isalpha - Is alphabetic - Check if a character is alphabetic.
.SH DECLARATION
.PP
.nf
\f[C]
# include <stdbool.h>
# include <stdint.h>
# include <uchar.h>
extern bool u8c_isalpha(uint_least8_t * const res,char32_t const chr);
\f[R]
.fi
.SH DESCRIPTION
.PP
.SH VERSION
.PP
u8c X
