.TH "u8c_u8free" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_u8free - UTF-8 free - Deallocate UTF-8 string and set it to \f[B]NULL\f[R].
.SH DECLARATION
.PP
.nf
\f[C]
/* # include <u8c/u8.h> */
# include <stdbool.h>
extern bool u8c_u8free(unsigned char const * * const u8);
\f[R]
.fi
.SH DESCRIPTION
.PP
.SH VERSION
.PP
u8c 16
