.TH "u8c_u32fndpat" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_u32fndpat - UTF-32 find pattern - Find the first occurence of an UTF-32 pattern (string) in an UTF-32 string.
.SH DECLARATION
.PP
.nf
\f[C]
/* # include <u8c/u32.h> */
# include <stdbool.h>
# include <stddef.h>
# include <uchar.h>
extern bool u8c_u32fndpat(size_t * const pos,char32_t const * const in,char32_t const * const pat);
\f[R]
.fi
.SH DESCRIPTION
.PP
.SH VERSION
.PP
u8c 16
