.TH "u8c_u8alloc" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_u8alloc - UTF-8 allocate - Allocate UTF-8 string.
.SH DECLARATION
.PP
.nf
\f[C]
/* # include <u8c/u8.h> */
# include <stdbool.h>
# include <stddef.h>
extern bool u8c_u8alloc(unsigned char * * const u32,size_t const sz);
\f[R]
.fi
.SH DESCRIPTION
.PP
.SH VERSION
.PP
u8c 16
