.TH "u8c_vfmt" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_vfmt - Variadic format - Format UTF-32 string.
.SH DECLARATION
.PP
.nf
\f[C]
/* # include <u8c/fmt.h> */
# include <stdarg.h>
# include <stdbool.h>
# include <stddef.h>
# include <uchar.h>
extern bool u8c_vfmt(size_t * const sz,char32_t const * * const out,char32_t const * const in,va_list args);
\f[R]
.fi
.SH DESCRIPTION
.PP
.SH VERSION
.PP
u8c 2
