.TH "u8c_u32substr" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_u32substr - UTF-32 sub-string - Get sub-string of an UTF-32 string.
.SH DECLARATION
.PP
.nf
\f[C]
/* # include <u8c/u32.h> */
# include <stdbool.h>
# include <stddef.h>
# include <uchar.h>
extern bool u8c_u32substr(char32_t const * * const out,size_t const start,size_t const len,char32_t const * const in);
\f[R]
.fi
.SH DESCRIPTION
.PP
.SH VERSION
.PP
u8c 16
