.TH "u8c_end" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_end - End - Finalise u8c and clean up.
.SH DECLARATION
.PP
.nf
\f[C]
/* # include <u8c/main.h> */
# include <stdbool.h>
extern bool u8c_end(void);
\f[R]
.fi
.SH DESCRIPTION
.PP
The function \f[B]u8c_end\f[R] ends the current u8c session.
.PP
If \f[B]u8c_end\f[R] is called before \f[B]u8c_init\f[R], \f[B]false\f[R] is returned, and nothing has happened.
.PP
If it is called after it has already been called, unless \f[B]u8c_init\f[R] has been called in the meantime, \f[B]false\f[R] is returned, and nothing has happened.
.PP
Even if \f[B]u8c_thrdsafe\f[R] evaluates to \f[B]true\f[R], this function is never thread-safe.
.SH VERSION
.PP
u8c 2
