.TH "u8c_fmttyp" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_fmttyp - Format type - Format specifier to be used by \f[C]u8c_fmt\f[R] or \f[C]u8c_vfmt\f[R].
.SH DECLARATION
.PP
.nf
\f[C]
enum u8c_fmttyp {
	u8c_fmttyp_bgcol,
	u8c_fmttyp_bgcol0,
	u8c_fmttyp_bool,
	u8c_fmttyp_byt,
	u8c_fmttyp_chr,
	u8c_fmttyp_fgcol,
	u8c_fmttyp_fgcol0,
	u8c_fmttyp_int,
	u8c_fmttyp_int16,
	u8c_fmttyp_int32,
	u8c_fmttyp_int64,
	u8c_fmttyp_int8,
	u8c_fmttyp_llong,
	u8c_fmttyp_long,
	u8c_fmttyp_sbyt,
	u8c_fmttyp_shrt,
	u8c_fmttyp_str,
	u8c_fmttyp_sz,
	u8c_fmttyp_tm,
	u8c_fmttyp_ubyt,
	u8c_fmttyp_uint,
	u8c_fmttyp_uint16,
	u8c_fmttyp_uint32,
	u8c_fmttyp_uint64,
	u8c_fmttyp_uint8,
	u8c_fmttyp_ulong,
	u8c_fmttyp_ullong,
	u8c_fmttyp_ushrt,
};
\f[R]
.fi
.SH DESCRIPTION
.PP
.SH VERSION
.PP
u8c 0
