.TH "u8c_print" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_print - Print - Format UTF-32 and print it to file.
.SH DECLARATION
.PP
.nf
\f[C]
# include <stdbool.h>
# include <stdio.h>
# include <uchar.h>
extern bool u8c_print(FILE * fp,char32_t const * const msg,...);
\f[R]
.fi
.SH DESCRIPTION
.PP
.SH VERSION
.PP
u8c 2
