.TH "u8c_abrtfn" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_abrtfn - Abort functions - Abort program with diagnostic information.
.SH DECLARATION
.PP
.nf
\f[C]
/* # include <u8c/main.h> */
# include <stdbool.h
# include <stdnoreturn.h>
# include <uchar.h>
extern noreturn bool u8c_abrtfn(char const * const fl,long const ln,char const * const fn,char const * const why);
\f[R]
.fi
.SH DESCRIPTION
.PP
The function \f[B]u8c_abrtfn\f[R] aborts the program and prints diagnostic infiormation to \f[B]stderr\f[R].
.PP
\f[B]__FILE__\f[R] is to be passed at \f[B]fl\f[R], \f[B](long)__LINE__\f[R] at \f[B]ln\f[R], and \f[B]__func__\f[R] at \f[B]fn\f[R]. A standard string (\f[B]char const *\f[R]) must be passed at \f[B]why\f[R], which explains the reason for aborting.
.PP
All arguments are printed, in the end followed by a timestamp representing the number of seconds passed since the current epoch (as returned by \f[B]time(NULL)\f[R]).
.PP
It's recommended to use the convenience macro \f[B]u8c_abrt\f[R], as it expands to a valid call to \f[B]u8c_abrt\f[R].
.SH VERSION
.PP
u8c 16 (as \f[B]u8c_abrt\f[R]), u8c 21
