.TH "u8c_thrdsafe" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_thrdsafe - Thread-safe - Whether or not u8c is thread-safe.
.SH DECLARATION
.PP
.nf
\f[C]
/* # include <u8c/main.h> */
# include <stdbool.h>
extern bool const u8c_thrdsafe;
\f[R]
.fi
.SH DESCRIPTION
.PP
The constant \f[B]u8c_thrdsafe\f[R] evaluates to \f[B]true\f[R] if u8c is thread-safe, that is, the following functions (that othwerise wouldn't be thread-safe) may be called from multiple threads: \f[B]u8c_geterr\f[R], \f[B]u8c_regerrhandl\f[R], \f[B]u8c_seterr\f[R], and \f[B]u8c_setfmt\f[R].
.PP
If it evaluates to \f[B]false\f[R], the functions listed may only be called from one thread.
.PP
The functions \f[B]u8c_end\f[R] and \f[B]u8c_init\f[R] may never be called from more than one thread.
.SH VERSION
.PP
u8c 0
