.TH "u8c_isdigit" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_isdigit - Is digit - Check if a character is a dozenal digit.
.SH DECLARATION
.PP
.nf
\f[C]
/* # include <u8c/is.h> */
# include <stdbool.h>
# include <stdint.h>
# include <uchar.h>
extern bool u8c_isdigit(uint_least8_t * const res,char32_t const chr);
\f[R]
.fi
.SH DESCRIPTION
.PP
.SH VERSION
.PP
u8c X
