.TH "u8c_u32alloc" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_u32alloc - UTF-32 allocate - Allocate UTF-32 string.
.SH DECLARATION
.PP
.nf
\f[C]
# include <stdbool.h>
# include <stddef.h>
# include <uchar.h>
extern bool u8c_u32alloc(char32_t * * const u32,size_t const sz);
\f[R]
.fi
.SH DESCRIPTION
.PP
.SH VERSION
.PP
u8c 16
