.TH "u8c_u32max" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_u32max - UTF-32 maximum - Maximum valid UTF-32 value.
.SH DECLARATION
.PP
.nf
\f[C]
/* # include <u8c/u32.h> */
# include <uchar.h>
static char32_t const u8c_u32max = U'\x10FFFF';
\f[R]
.fi
.SH DESCRIPTION
.PP
.SH VERSION
.PP
u8c 16 (as \f[B]u8c_unimax\f[R]), u8c 21
