.TH "u8c_setfmt" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_setfmt - Set format - Set format to be used by \f[B]u8c_fmt\f[R] and company.
.SH DECLARATION
.PP
.nf
\f[C]
/* # include <u8c/fmt.h> */
# include <stdbool.h>
# include <stdint.h>
extern bool u8c_setfmt(uint_least8_t const base,uint_least8_t const endian);
\f[R]
.fi
.SH DESCRIPTION
.PP
.SH VERSION
.PP
u8c 16
