.TH "u8c_u16alloc" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_u16alloc - UTF-16 allocate - Allocate UTF-16 string.
.SH DECLARATION
.PP
.nf
\f[C]
/* # include <u8c/u16.h> */
# include <stdbool.h>
# include <stddef.h>
# include <uchar.h>
extern bool u8c_u16alloc(char16_t * * const u16,size_t const sz);
\f[R]
.fi
.SH DESCRIPTION
.PP
.SH VERSION
.PP
u8c 20
