.TH "u8c_dbg" "3" "" "u8c" "u8c API Manual"
.SH NAME
.PP
u8c_dbg - Debug - Whether or not the library is in debug mode.
.SH DECLARATION
.PP
.nf
\f[C]
/* # include <u8c/main.h> */
# include <stdbool.h>
extern bool const u8c_dbg;
\f[R]
.fi
.SH DESCRIPTION
.PP
The constant \f[B]u8c_dbg\f[R] has value \f[B]false\f[R] if u8c has been compiled with debugging disabled, otherwise \f[B]true\f[R].
.SH VERSION
.PP
u8c 0 (as \f[B]u8c_debug\f[R]), u8c 16
